TRUNCATE TABLE Errands
TRUNCATE TABLE ErrandStatus1
TRUNCATE TABLE Departments
TRUNCATE TABLE Employees
TRUNCATE TABLE Samples
TRUNCATE TABLE Pictures
TRUNCATE TABLE Sequences

SELECT * FROM Errands
SELECT * FROM ErrandStatus1
SELECT * FROM Departments
SELECT * FROM Employees
SELECT * FROM Samples
SELECT * FROM Pictures
SELECT * FROM Sequences
